---
- hosts: all
  gather_facts: False
  tasks:
    - name: Run NMAP using Anisible commnd module
      command: python3 portscan.py {{inventory_hostname}}
      register: output
    - debug:
        var: output
